stages:
  - build
  - submitjob

buildjava:
  stage: build
  script:
    - "cd java"
    - "javac -Xdiags:verbose -classpath $(hadoop classpath) -d . JobOne.java"
    - "jar cf jobone.jar class/bigdata/jobone/JobOne*.class"
    - "javac -Xdiags:verbose -classpath $(hadoop classpath) -d . JobTwo.java"
    - "jar cf jobtwo.jar class/bigdata/jobtwo/JobTwo*.class"
  artifacts:
    paths:
      - jobone.jar
      - jobtwo.jar

submit:
  stage: submitjob
  script:
    - "gcloud dataproc jobs submit hadoop --cluster cluster-05bd --jar java/jobone.jar -- JobOne data dataout1 london.csv outfile"
    - "gcloud dataproc jobs submit hadoop --cluster cluster-05bd --jar java/jobtwo.jar -- JobTwo data dataout2 london.csv outfile"
