before_script:
  - "mkdir jar class"

stages:
  - build
  - submitjob

buildjava:
  stage: build
  script:
    - "javac -Xdiags:verbose -classpath $(hadoop classpath) -d class/ src/bigdata/jobone/JobOne.java"
    - "jar cf jar/jobone.jar class/bigdata/jobone/JobOne*.class"
    - "javac -Xdiags:verbose -classpath $(hadoop classpath) -d class/ src/bigdata/jobtwo/JobTwo.java"
    - "jar cf jar/jobtwo.jar class/bigdata/jobtwo/JobTwo*.class"
  artifacts:
    paths:
      - jar/
      - class/

submit:
  stage: submitjob
  script:
    - "gcloud dataproc jobs submit hadoop --cluster cluster-05bd --jar jar/jobone.jar -- data dataout1 london.csv outfile"
    - "gcloud dataproc jobs submit hadoop --cluster cluster-05bd --jar jar/jobtwo.jar -- data dataout2 london.csv outfile"
